export const AUTH_MESSAGES = {
  LOGIN_TITLE: "Welcome Back",
  REGISTER_TITLE: "Join Us",
  LOGIN_BUTTON: "Login",
  REGISTER_BUTTON: "Register",
  LOGGING_IN: "Logging in...",
  REGISTERING: "Registering...",
  GOOGLE_SIGN_IN: "Sign in with Google",
  LOGIN_PROMPT: "Need an account?",
  REGISTER_PROMPT: "Already have an account?",
  LOGIN_LINK: "Register",
  REGISTER_LINK: "Login",
  LOGIN_SUCCESS: "Logged in successfully!",
  REGISTER_SUCCESS: "Registered successfully! Please log in.",
  LOGIN_ERROR: "Login failed. Check your credentials.",
  REGISTER_ERROR: "Registration failed.",
  GOOGLE_LOGIN_SUCCESS: "Logged in with Google successfully!",
  GOOGLE_LOGIN_ERROR: "Google login failed!",
};
