export const DISCOUNT_MESSAGES = {
    TITLE: "Discount Management",
    ADD_NEW: "Add New Discount",
    ALL_DISCOUNTS: "All Discounts",
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    NO_PRODUCTS: "No specific products (applies to all)",
    ERROR: "Error loading discounts",
    ADMIN_REQUIRED: "Admin access required!",
    CREATE_SUCCESS: "Discount created successfully!",
    UPDATE_SUCCESS: "Discount updated successfully!",
    DELETE_SUCCESS: "Discount deleted successfully!",
    BULK_UPDATE_SUCCESS: "Discounts updated successfully!",
    CREATE_ERROR: "Failed to create discount.",
    UPDATE_ERROR: "Failed to update discount.",
    DELETE_ERROR: "Failed to delete discount.",
    BULK_UPDATE_ERROR: "Failed to update discounts.",
    CODE_REQUIRED: "Discount code is required.",
    VALUE_POSITIVE: "Discount value must be a positive number.",
    MIN_ORDER_NEGATIVE: "Minimum order value cannot be negative.",
    MAX_DISCOUNT_NEGATIVE: "Maximum discount amount cannot be negative.",
    START_DATE_REQUIRED: "Start date is required.",
    END_DATE_INVALID: "End date cannot be before start date.",
  };
  
  export const DISCOUNT_BUTTONS = {
    ADD: "Add Discount",
    SAVE: "Save",
    CANCEL: "Cancel",
    ACTIVATE: "Activate",
    DEACTIVATE: "Deactivate",
    PREV: "Previous",
    NEXT: "Next",
  };